version: '3'

services:
  db:
    image: mdillon/postgis
    container_name: db
    environment:
      - POSTGRES_USER=ldoo
      - POSTGRES_PASSWORD=ldoo123
      - POSTGRES_DB=ldoodb
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: