# Generated by Django 3.2.13 on 2022-06-11 23:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubichallenge', '0003_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('average_speed', models.FloatField()),
                ('intensity', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('characterization', models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='low', max_length=8)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubichallenge.segment')),
            ],
        ),
    ]
