# Generated by Django 3.2.13 on 2022-06-11 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubichallenge', '0004_averagespeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagespeed',
            name='intensity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
