# Generated by Django 3.2.13 on 2022-06-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubichallenge', '0007_auto_20220612_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='end',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='ubichallenge.location'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='ubichallenge.location'),
        ),
    ]
