# Generated by Django 3.2.13 on 2022-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubichallenge', '0009_alter_location_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
