# Generated by Django 3.2.13 on 2022-06-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubichallenge', '0010_modela'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelA',
        ),
    ]
