# Generated by Django 3.2.13 on 2022-06-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubichallenge', '0011_delete_modela'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('start', 'end')},
        ),
    ]
